# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heisenberg < Formula
  desc "AI-powered test failure analysis for GitHub repositories"
  homepage "https://github.com/kamilpajak/heisenberg"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.1.1/heisenberg_0.1.1_darwin_x86_64.tar.gz"
      sha256 "d811910251223bbe5108e357fda7dce5dd6030d0d2f72181f7b358ce7833cbe1"

      def install
        bin.install "heisenberg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.1.1/heisenberg_0.1.1_darwin_arm64.tar.gz"
      sha256 "5d8776981a6dec02d0d73cd320448515865eecd3536f4b268fbf5317ae69a621"

      def install
        bin.install "heisenberg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.1.1/heisenberg_0.1.1_linux_x86_64.tar.gz"
      sha256 "f36108a2c53d6370c5b5f58a148168497eaebb2b47d651788a1bef2aaa377137"
      def install
        bin.install "heisenberg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.1.1/heisenberg_0.1.1_linux_arm64.tar.gz"
      sha256 "80a3a2cf662a57f61dc96a1bb34face3125d8ef4e7cf63c843d6d0ac6a846431"
      def install
        bin.install "heisenberg"
      end
    end
  end

  test do
    system "#{bin}/heisenberg", "--help"
  end
end
