# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heisenberg < Formula
  desc "AI-powered test failure analysis for GitHub repositories"
  homepage "https://github.com/kamilpajak/heisenberg"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.5.0/heisenberg_0.5.0_darwin_x86_64.tar.gz"
      sha256 "b20fdcc25aec7da820212f0fa48449c29c9854dba62f1c1572677d5e7014996d"

      define_method(:install) do
        bin.install "heisenberg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.5.0/heisenberg_0.5.0_darwin_arm64.tar.gz"
      sha256 "1ee6203560285d7e65738a920c510beaba71ade3764f9b92d221ed8940a2a08b"

      define_method(:install) do
        bin.install "heisenberg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.5.0/heisenberg_0.5.0_linux_x86_64.tar.gz"
      sha256 "6c5e4952bacca2e3a7edc0866047aaa5c11d032374834beceb6032b348c5643a"
      define_method(:install) do
        bin.install "heisenberg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.5.0/heisenberg_0.5.0_linux_arm64.tar.gz"
      sha256 "c049821d03a45fc903d088f556cc4430179a02b2e2fd2d1c008dd760f1395ecc"
      define_method(:install) do
        bin.install "heisenberg"
      end
    end
  end

  test do
    system "#{bin}/heisenberg", "--help"
  end
end
