# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Heisenberg < Formula
  desc "AI-powered test failure analysis for GitHub repositories"
  homepage "https://github.com/kamilpajak/heisenberg"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.3.1/heisenberg_0.3.1_darwin_x86_64.tar.gz"
      sha256 "a8711360a2fcd6f83c953f48b454800d8f4799fb23ba349378ec94399f772967"

      define_method(:install) do
        bin.install "heisenberg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.3.1/heisenberg_0.3.1_darwin_arm64.tar.gz"
      sha256 "351f2259b884e1c0163c94846bfe73ec5a8bb12ee1e63196c0a5469bab2bbc6e"

      define_method(:install) do
        bin.install "heisenberg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.3.1/heisenberg_0.3.1_linux_x86_64.tar.gz"
      sha256 "690c2af018e431e99015cfaa1e577b889eadbde679d9a5f6fd4ffa1d8e625fc8"
      define_method(:install) do
        bin.install "heisenberg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kamilpajak/heisenberg/releases/download/v0.3.1/heisenberg_0.3.1_linux_arm64.tar.gz"
      sha256 "ba63ff8e329e52a153ce7cfc33ff7d6725c28c4324c85130ad576e0276d706f8"
      define_method(:install) do
        bin.install "heisenberg"
      end
    end
  end

  test do
    system "#{bin}/heisenberg", "--help"
  end
end
